package com.manasmalla.ahamsvasth;

public class Ingredient {
    String ingredientName;
    int ingredientDrawable;

    public void createIngredient(String name, int drawable) {
        this.ingredientName = name;
        this.ingredientDrawable = drawable;
    }

    public String getIngredientName() {
        return ingredientName;
    }

    public static Ingredient onion, uradDal, ragiFlour, salt, oil, riceFlour, curd, suji, ginger, greenChilli, curryLeaf, coriender, jeera, pepper, water, carrot, oats;
    public static Ingredient chanaDal, mustardSeeds, greenPeas, frenchBeans, tomato, turmeric, redChilliPowder, sweetCorn, capsicum, gingergarlicPaste, corienderPowder, jeeraPowder;
    public static Ingredient cloves, elachi, bayleaf, cinamon, starAnise, shahJeera, basmati, cashew, paneer, chicken, fish, mutton, prawns, multigrainFlour, mint, spinach, fenugreekSeeds;
    public static Ingredient ghee, brownRice, eggs, pulses, hing, rice, seasme, lemonJuice, coconut, vegetables, garam_masala, aamchur, ajwain, lentils, moongdal, redChilli, garlic, tamrindJuice, toordal, jaggery, sambarPowder, groundnut, amla;
    public static Ingredient wheat, nuts, chatMasaala, rajma, chowli, cucumber, pomegranate, oliveoil, banana, brownSugar, bakingPowder, bakingsoda, vanillaEssence, raisins, butter, honey;
    public static Ingredient quinoa, flax, brocoli, mushroom, tulasi, masoordal, vinegar,blackbeans,tabasco,sweetLime, papaya, methiSprouts,corienderSeeds, ladyfinger, pearlMilletFlour;
    public static Ingredient kasuriMethi, cream, badam;
    public void getIngredients() {
        wheat = new Ingredient();
        nuts = new Ingredient();
        masoordal = new Ingredient();
        vinegar = new Ingredient();
        blackbeans = new Ingredient();
        tabasco = new Ingredient();
        sweetLime = new Ingredient();
        papaya = new Ingredient();
        methiSprouts = new Ingredient();
        chatMasaala = new Ingredient();
        rajma = new Ingredient();
        chowli = new Ingredient();
        cucumber = new Ingredient();
        pomegranate = new Ingredient();
        oliveoil = new Ingredient();
        banana = new Ingredient();
        brownSugar = new Ingredient();
        bakingPowder = new Ingredient();
        bakingsoda = new Ingredient();
        quinoa = new Ingredient();
        flax = new Ingredient();
        brocoli = new Ingredient();
        mushroom = new Ingredient();
        tulasi = new Ingredient();
        vanillaEssence = new Ingredient();
        raisins = new Ingredient();
        butter = new Ingredient();
        honey = new Ingredient();
        onion = new Ingredient();
        uradDal = new Ingredient();
        ragiFlour = new Ingredient();
        salt = new Ingredient();
        oil = new Ingredient();
        riceFlour = new Ingredient();
        curd = new Ingredient();
        suji = new Ingredient();
        ginger = new Ingredient();
        greenChilli = new Ingredient();
        curryLeaf = new Ingredient();
        coriender = new Ingredient();
        jeera = new Ingredient();
        pepper = new Ingredient();
        water = new Ingredient();
        carrot = new Ingredient();
        oats = new Ingredient();
        chanaDal = new Ingredient();
        mustardSeeds = new Ingredient();
        greenPeas = new Ingredient();
        frenchBeans = new Ingredient();
        tomato = new Ingredient();
        turmeric = new Ingredient();
        redChilliPowder = new Ingredient();
        sweetCorn = new Ingredient();
        capsicum = new Ingredient();
        gingergarlicPaste = new Ingredient();
        corienderPowder = new Ingredient();
        jeeraPowder = new Ingredient();
        cloves = new Ingredient();
        elachi = new Ingredient();
        bayleaf = new Ingredient();
        cinamon = new Ingredient();
        starAnise = new Ingredient();
        shahJeera = new Ingredient();
        basmati = new Ingredient();
        cashew = new Ingredient();
        paneer = new Ingredient();
        chicken = new Ingredient();
        fish = new Ingredient();
        mutton = new Ingredient();
        prawns = new Ingredient();
        multigrainFlour = new Ingredient();
        mint = new Ingredient();
        spinach = new Ingredient();
        fenugreekSeeds = new Ingredient();
        brownRice = new Ingredient();
        ghee = new Ingredient();
        eggs = new Ingredient();
        pulses = new Ingredient();
        hing = new Ingredient();
        rice = new Ingredient();
        seasme = new Ingredient();
        lemonJuice = new Ingredient();
        coconut = new Ingredient();
        vegetables = new Ingredient();
        garam_masala = new Ingredient();
        aamchur = new Ingredient();
        ajwain = new Ingredient();
        lentils = new Ingredient();
        moongdal = new Ingredient();
        redChilli = new Ingredient();
        garlic = new Ingredient();
        toordal = new Ingredient();
        tamrindJuice = new Ingredient();
        jaggery = new Ingredient();
        sambarPowder = new Ingredient();
        amla = new Ingredient();
        groundnut = new Ingredient();
        corienderSeeds = new Ingredient();
        ladyfinger = new Ingredient();
        pearlMilletFlour = new Ingredient();
        kasuriMethi = new Ingredient();
        badam = new Ingredient();
        cream = new Ingredient();
        coriender.createIngredient("Coriander", R.drawable.food_bowl);
        amla.createIngredient("Amla", R.drawable.food_bowl);
        groundnut.createIngredient("Groundnut", R.drawable.food_bowl);
        jaggery.createIngredient("Jaggery", R.drawable.food_bowl);
        sambarPowder.createIngredient("Sambar Powder", R.drawable.food_bowl);
        toordal.createIngredient("Toor Dal", R.drawable.food_bowl);
        tamrindJuice.createIngredient("Tamrind Juice", R.drawable.food_bowl);
        redChilli.createIngredient("Red Chilli", R.drawable.food_bowl);
        garlic.createIngredient("Garlic", R.drawable.food_bowl);
        moongdal.createIngredient("Moong Dal", R.drawable.food_bowl);
        lentils.createIngredient("Mixed Lentils", R.drawable.food_bowl);
        ajwain.createIngredient("Ajwain", R.drawable.food_bowl);
        aamchur.createIngredient("Aamchur", R.drawable.food_bowl);
        garam_masala.createIngredient("Garam Masala", R.drawable.food_bowl);
        vegetables.createIngredient("Veggies", R.drawable.food_bowl);
        onion.createIngredient("Onion", R.drawable.apple_logo);
        uradDal.createIngredient("Urad Dal Paste", R.drawable.apple_logo);
        ragiFlour.createIngredient("Ragi Flour", R.drawable.apple_logo);
        salt.createIngredient("Salt", R.drawable.apple_logo);
        oil.createIngredient("Oil", R.drawable.apple_logo);
        riceFlour.createIngredient("Rice Flour", R.drawable.apple_logo);
        curd.createIngredient("Curd", R.drawable.apple_logo);
        suji.createIngredient("Suji", R.drawable.apple_logo);
        ginger.createIngredient("Ginger", R.drawable.apple_logo);
        greenChilli.createIngredient("Green Chilli", R.drawable.apple_logo);
        curryLeaf.createIngredient("Curry Leaves", R.drawable.apple_logo);
        jeera.createIngredient("Jeera", R.drawable.apple_logo);
        pepper.createIngredient("Pepper", R.drawable.apple_logo);
        water.createIngredient("Water", R.drawable.ic_water);
        carrot.createIngredient("Carrot", R.drawable.ic_water);
        oats.createIngredient("Oats", R.drawable.ic_water);
        chanaDal.createIngredient("Chana Dal", R.drawable.ic_water);
        mustardSeeds.createIngredient("Mustard Seeds", R.drawable.ic_water);
        greenPeas.createIngredient("Green Peas", R.drawable.ic_water);
        frenchBeans.createIngredient("French Beans", R.drawable.ic_water);
        tomato.createIngredient("Tomato", R.drawable.ic_water);
        turmeric.createIngredient("Turmeric", R.drawable.ic_water);
        redChilliPowder.createIngredient("Red Chilli Powder", R.drawable.ic_water);
        sweetCorn.createIngredient("Sweet Corn", R.drawable.ic_water);
        capsicum.createIngredient("Capsicum", R.drawable.ic_water);
        gingergarlicPaste.createIngredient("Ginger Garlic Paste", R.drawable.ic_water);
        corienderPowder.createIngredient("Coriender Powder", R.drawable.ic_water);
        jeeraPowder.createIngredient("Jeera Powder", R.drawable.ic_water);
        cloves.createIngredient("Cloves", R.drawable.ic_water);
        elachi.createIngredient("Elachi", R.drawable.ic_water);
        bayleaf.createIngredient("BayLeaf", R.drawable.ic_water);
        cinamon.createIngredient("Cinnamon", R.drawable.ic_water);
        starAnise.createIngredient("Star Anise", R.drawable.ic_water);
        shahJeera.createIngredient("Shah Jeera", R.drawable.ic_water);
        basmati.createIngredient("Basmati Rice", R.drawable.ic_water);
        cashew.createIngredient("Cashew", R.drawable.ic_water);
        paneer.createIngredient("Paneer", R.drawable.ic_water);
        chicken.createIngredient("Chicken", R.drawable.ic_water);
        fish.createIngredient("Fish", R.drawable.ic_water);
        mutton.createIngredient("Mutton", R.drawable.ic_water);
        prawns.createIngredient("Prawns", R.drawable.ic_water);
        multigrainFlour.createIngredient("Multigrain Flour", R.drawable.ic_water);
        mint.createIngredient("Mint", R.drawable.ic_water);
        spinach.createIngredient("Spinach", R.drawable.ic_water);
        fenugreekSeeds.createIngredient("Fenugreek Seeds", R.drawable.ic_water);
        brownRice.createIngredient("Brown Rice", R.drawable.ic_water);
        ghee.createIngredient("Ghee", R.drawable.ic_water);
        eggs.createIngredient("Eggs", R.drawable.ic_water);
        pulses.createIngredient("Pulses", R.drawable.ic_water);
        hing.createIngredient("Hing", R.drawable.ic_water);
        rice.createIngredient("Rice", R.drawable.ic_water);
        seasme.createIngredient("Seasme Seeds", R.drawable.ic_water);
        lemonJuice.createIngredient("Lemon Juice", R.drawable.ic_water);
        coconut.createIngredient("Coconut", R.drawable.ic_water);

        wheat.createIngredient("Wheat", R.drawable.ic_water);
        nuts.createIngredient("Nuts", R.drawable.ic_water);
        chatMasaala.createIngredient("Chat Masala", R.drawable.ic_water);
        rajma.createIngredient("Rajma", R.drawable.ic_water);
        chowli.createIngredient("Chowli Beans", R.drawable.ic_water);
        cucumber.createIngredient("Cucumber", R.drawable.ic_water);
        pomegranate.createIngredient("Pomegranate", R.drawable.ic_water);
        oliveoil.createIngredient("Olive Oil", R.drawable.ic_water);
        banana.createIngredient("Banana", R.drawable.ic_water);
        brownSugar.createIngredient("Brown Sugar", R.drawable.ic_water);
        bakingPowder.createIngredient("Baking Powder", R.drawable.ic_water);
        bakingsoda.createIngredient("Baking Soda", R.drawable.ic_water);
        vanillaEssence.createIngredient("Vanilla Essence", R.drawable.ic_water);
        raisins.createIngredient("Raisins", R.drawable.ic_water);
        butter.createIngredient("Butter", R.drawable.ic_water);
        honey.createIngredient("Honey", R.drawable.ic_water);
        quinoa.createIngredient("Quinoa", R.drawable.ic_water);
        flax.createIngredient("Flax", R.drawable.ic_water);
        brocoli.createIngredient("Brocoli", R.drawable.ic_water);
        mushroom.createIngredient("Mushroom", R.drawable.ic_water);
        tulasi.createIngredient("Tulasi", R.drawable.ic_water);

        masoordal.createIngredient("Masoor Dal", R.drawable.ic_water);
        vinegar.createIngredient("Vinegar", R.drawable.ic_water);
        blackbeans.createIngredient("Black Beans", R.drawable.ic_water);
        tabasco.createIngredient("Tabasco Sauce", R.drawable.ic_water);
        sweetLime.createIngredient("Sweet Lime", R.drawable.ic_water);
        papaya.createIngredient("Papaya", R.drawable.ic_water);
        methiSprouts.createIngredient("Methi Sprouts", R.drawable.ic_water);

        corienderSeeds.createIngredient("Coriender Seeds", R.drawable.ic_water);
        ladyfinger.createIngredient("Ladyfingers", R.drawable.ic_water);
        pearlMilletFlour.createIngredient("Pearl Millet Flour", R.drawable.food_bowl);

        kasuriMethi.createIngredient("Kasuri Methi", R.drawable.food_bowl);
        badam.createIngredient("Almonds", R.drawable.food_bowl);
        cream.createIngredient("Fresh Cream", R.drawable.food_bowl);
    }
}
