package com.manasmalla.ahamsvasth;

public class Ingredient {
    String ingredientName;
    int ingredientDrawable;
    public void createIngredient(String name, int drawable){
        this.ingredientName = name;
        this.ingredientDrawable = drawable;
    }

    public static Ingredient onion,uradDal, ragiFlour, salt, oil, riceFlour, curd, suji, ginger, greenChilli, curryLeaf, coriender, jeera, pepper, water, carrot, oats;
    public static Ingredient chanaDal, mustardSeeds, greenPeas, frenchBeans, tomato, turmeric, redChilliPowder, sweetCorn, capsicum, gingergarlicPaste, corienderPowder, jeeraPowder;
    public static Ingredient cloves, elachi, bayleaf, cinamon, starAnise, shahJeera, basmati, cashew, paneer, chicken, fish, mutton, prawns, multigrainFlour, mint, spinach, fenugreekSeeds;
    public static Ingredient ghee, brownRice, eggs, pulses, hing, rice, seasme, lemonJuice, coconut;
    public void getIngredients(){
        onion = new Ingredient();
        uradDal = new Ingredient();
        ragiFlour = new Ingredient();
        salt = new Ingredient();
        oil = new Ingredient();
        riceFlour = new Ingredient();
        curd = new Ingredient();
        suji = new Ingredient();
        ginger = new Ingredient();
        greenChilli = new Ingredient();
        curryLeaf = new Ingredient();
        coriender = new Ingredient();
        jeera = new Ingredient();
        pepper = new Ingredient();
        water = new Ingredient();
        carrot = new Ingredient();
        oats = new Ingredient();
        chanaDal = new Ingredient();
        mustardSeeds = new Ingredient();
        greenPeas = new Ingredient();
        frenchBeans = new Ingredient();
        tomato = new Ingredient();
        turmeric = new Ingredient();
        redChilliPowder = new Ingredient();
        sweetCorn = new Ingredient();
        capsicum = new Ingredient();
        gingergarlicPaste = new Ingredient();
        corienderPowder = new Ingredient();
        jeeraPowder = new Ingredient();
        cloves = new Ingredient();
        elachi = new Ingredient();
        bayleaf = new Ingredient();
        cinamon = new Ingredient();
        starAnise = new Ingredient();
        shahJeera = new Ingredient();
        basmati = new Ingredient();
        cashew = new Ingredient();
        paneer = new Ingredient();
        chicken = new Ingredient();
        fish = new Ingredient();
        mutton = new Ingredient();
        prawns = new Ingredient();
        multigrainFlour = new Ingredient();
        mint = new Ingredient();
        spinach = new Ingredient();
        fenugreekSeeds = new Ingredient();
        brownRice = new Ingredient();
        ghee = new Ingredient();
        eggs = new Ingredient();
        pulses = new Ingredient();
        hing = new Ingredient();
        rice = new Ingredient();
        seasme = new Ingredient();
        lemonJuice = new Ingredient();
        coconut = new Ingredient();
        onion.createIngredient("Onion", R.drawable.apple_logo);
        uradDal.createIngredient("Urad Dal Paste", R.drawable.apple_logo);
        ragiFlour.createIngredient("Ragi Flour", R.drawable.apple_logo);
        salt.createIngredient("Salt", R.drawable.apple_logo);
        oil.createIngredient("Oil", R.drawable.apple_logo);
        riceFlour.createIngredient("Rice Flour", R.drawable.apple_logo);
        curd.createIngredient("Curd", R.drawable.apple_logo);
        suji.createIngredient("Suji", R.drawable.apple_logo);
        ginger.createIngredient("Ginger", R.drawable.apple_logo);
        greenChilli.createIngredient("Green Chilli", R.drawable.apple_logo);
        curryLeaf.createIngredient("Curry Leaves", R.drawable.apple_logo);
        jeera.createIngredient("Jeera", R.drawable.apple_logo);
        pepper.createIngredient("Pepper", R.drawable.apple_logo);
        water.createIngredient("Water", R.drawable.ic_water);
        carrot.createIngredient("Carrot", R.drawable.ic_water);
        oats.createIngredient("Oats", R.drawable.ic_water);
        chanaDal.createIngredient("Chana Dal", R.drawable.ic_water);
        mustardSeeds.createIngredient("Mustard Seeds", R.drawable.ic_water);
        greenPeas.createIngredient("Green Peas", R.drawable.ic_water);
        frenchBeans.createIngredient("French Beans", R.drawable.ic_water);
        tomato.createIngredient("Tomato", R.drawable.ic_water);
        turmeric.createIngredient("Turmeric", R.drawable.ic_water);
        redChilliPowder.createIngredient("Red Chilli Powder", R.drawable.ic_water);
        sweetCorn.createIngredient("Sweet Corn", R.drawable.ic_water);
        capsicum.createIngredient("Capsicum", R.drawable.ic_water);
        gingergarlicPaste.createIngredient("Ginger Garlic Paste", R.drawable.ic_water);
        corienderPowder.createIngredient("Coriender Powder", R.drawable.ic_water);
        jeeraPowder.createIngredient("Jeera Powder", R.drawable.ic_water);
        cloves.createIngredient("Cloves", R.drawable.ic_water);
        elachi.createIngredient("Elachi", R.drawable.ic_water);
        bayleaf.createIngredient("BayLeaf", R.drawable.ic_water);
        cinamon.createIngredient("Cinnamon", R.drawable.ic_water);
        starAnise.createIngredient("Star Anise", R.drawable.ic_water);
        shahJeera.createIngredient("Shah Jeera", R.drawable.ic_water);
        basmati.createIngredient("Basmati Rice", R.drawable.ic_water);
        cashew.createIngredient("Cashew", R.drawable.ic_water);
        paneer.createIngredient("Paneer", R.drawable.ic_water);
        chicken.createIngredient("Chicken", R.drawable.ic_water);
        fish.createIngredient("Fish", R.drawable.ic_water);
        mutton.createIngredient("Mutton", R.drawable.ic_water);
        prawns.createIngredient("Prawns", R.drawable.ic_water);
        multigrainFlour.createIngredient("Multigrain Flour", R.drawable.ic_water);
        mint.createIngredient("Mint", R.drawable.ic_water);
        spinach.createIngredient("Spinach", R.drawable.ic_water);
        fenugreekSeeds.createIngredient("Fenugreek Seeds", R.drawable.ic_water);
        brownRice.createIngredient("Brown Rice", R.drawable.ic_water);
        ghee.createIngredient("Ghee", R.drawable.ic_water);
        eggs.createIngredient("Eggs", R.drawable.ic_water);
        pulses.createIngredient("Pulses", R.drawable.ic_water);
        hing.createIngredient("Hing", R.drawable.ic_water);
        rice.createIngredient("Rice", R.drawable.ic_water);
        seasme.createIngredient("Seasme Seeds", R.drawable.ic_water);
        lemonJuice.createIngredient("Lemon Juice", R.drawable.ic_water);
        coconut.createIngredient("Coconut", R.drawable.ic_water);
    }
}
